items:
  test_pickaxe:
    material: diamond_pickaxe
    name: '&#FFAA00Test pickaxe'
    lore:
    - ''
    - '&#555555(&#FFFF55#&#FFAA00%id%&#555555)'
    enchantments:
    - 'DIG_SPEED:5'
    count: 1